"""empty message

Revision ID: cb308fed5176
Revises: 
Create Date: 2019-02-19 00:48:23.591937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb308fed5176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('plink', sa.String(length=30), nullable=True),
    sa.Column('img1', sa.String(length=300), nullable=True),
    sa.Column('img2', sa.String(length=300), nullable=True),
    sa.Column('short', sa.String(length=200), nullable=True),
    sa.Column('about', sa.String(length=6000), nullable=True),
    sa.Column('rules', sa.String(length=6000), nullable=True),
    sa.Column('prereq', sa.String(length=6000), nullable=True),
    sa.Column('organiser', sa.String(length=40), nullable=True),
    sa.Column('prize1', sa.Integer(), nullable=True),
    sa.Column('prize2', sa.Integer(), nullable=True),
    sa.Column('prize3', sa.Integer(), nullable=True),
    sa.Column('pworth', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('team_limit', sa.Integer(), nullable=True),
    sa.Column('expense', sa.Integer(), nullable=True),
    sa.Column('incharge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_d_log',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('cat', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vid', 'cat', 'eid')
    )
    op.create_table('registrations',
    sa.Column('regid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.Column('cat', sa.Integer(), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('pay_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('regid')
    )
    op.create_table('staff',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vid', 'team')
    )
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('plink', sa.String(length=30), nullable=True),
    sa.Column('short', sa.String(length=200), nullable=True),
    sa.Column('about', sa.String(length=3000), nullable=True),
    sa.Column('person', sa.String(length=30), nullable=False),
    sa.Column('desig', sa.String(length=30), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.Column('picurl', sa.String(length=260), nullable=True),
    sa.Column('ppicurlsm', sa.String(length=260), nullable=True),
    sa.Column('ppicurllr', sa.String(length=260), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('incharge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('vid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fname', sa.String(length=30), nullable=True),
    sa.Column('lname', sa.String(length=30), nullable=True),
    sa.Column('ppic', sa.String(length=200), nullable=True),
    sa.Column('course', sa.String(length=200), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('college', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('school', sa.Boolean(), nullable=True),
    sa.Column('phno', sa.String(length=10), nullable=True),
    sa.Column('detailscomp', sa.Boolean(), nullable=True),
    sa.Column('educomp', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('lastseen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('plink', sa.String(length=30), nullable=True),
    sa.Column('short', sa.String(length=200), nullable=True),
    sa.Column('about', sa.String(length=3000), nullable=True),
    sa.Column('prereq', sa.String(length=3000), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('instructor', sa.String(length=40), nullable=True),
    sa.Column('abins', sa.String(length=300), nullable=True),
    sa.Column('vidurl', sa.String(length=400), nullable=True),
    sa.Column('img1', sa.String(length=200), nullable=True),
    sa.Column('img2', sa.String(length=200), nullable=True),
    sa.Column('img3', sa.String(length=200), nullable=True),
    sa.Column('lead', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('companylogo', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=10), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('incharge', sa.Integer(), nullable=True),
    sa.Column('support', sa.Integer(), nullable=True),
    sa.Column('d1stime', sa.DateTime(), nullable=True),
    sa.Column('d1enime', sa.DateTime(), nullable=True),
    sa.Column('d2stime', sa.DateTime(), nullable=True),
    sa.Column('d2enime', sa.DateTime(), nullable=True),
    sa.Column('d3stime', sa.DateTime(), nullable=True),
    sa.Column('d3enime', sa.DateTime(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('pub', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshops')
    op.drop_table('user')
    op.drop_table('talks')
    op.drop_table('staff')
    op.drop_table('registrations')
    op.drop_table('event_d_log')
    op.drop_table('contests')
    op.drop_table('college')
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
